export const REGISTER_LOADING ='REGISTER_LOADING';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const LOGOUT = 'LOGOUT';

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const UPLOAD_SHORTLET_LOADING = "UPLOAD_SHORTLET_LOADING";
export const UPLOAD_SHORTLET_SUCCESS = "UPLOAD_SHORTLET_SUCCESS";
export const UPLOAD_SHORTLET_FAIL = "UPLOAD_SHORTLET_FAIL";

export const FETCH_SHORTLET_LOADING = "FETCH_SHORTLET_LOADING";
export const FETCH_SHORTLET_SUCCESS = "FETCH_SHORTLET_SUCCESS";
export const FETCH_SHORTLET_FAIL = "FETCH_SHORTLET_FAIL";

export const FETCH_ONE_SHORTLET_LOADING = "FETCH_ONE_SHORTLET_LOADING";
export const FETCH_ONE_SHORTLET_SUCCESS = "FETCH_ONE_SHORTLET_SUCCESS";
export const FETCH_ONE_SHORTLET_FAIL = "FETCH_ONE_SHORTLET_FAIL";

export const GETLINK_FAIL = "GETLINK_FAIL";

export const ADD_BANK_LOADING = "ADD_BANK_LOADING"
export const ADD_BANK_SUCCESS = "ADD_BANK_SUCCESS"
export const ADD_BANK_FAIL = "ADD_BANK_FAIL";

export const GET_BANK_LOADING = "GET_BANK_LOADING";
export const GET_BANK_SUCCESS = "GET_BANK_SUCCESS";
export const GET_BANK_FAIL = "GET_BANK_FAIL";

export const WITHDRAWAL_LOADING = "WITHDRAWAL_LOADING";
export const WITHDRAWAL_SUCCESS = "WITHDRAWAL_SUCCESS";
export const WITHDRAWAL_FAIL = "WITHDRAWAL_FAIL";

export const GET_ME = "GET_ME";

export const GET_APARTMENT_LOADING = "GET_APARTMENT_LOADING";
export const GET_APARTMENT_SUCCESS = "GET_APARTMENT_SUCCESS";
export const GET_APARTMENT_FAIL = "GET_APARTMENT_FAIL";

export const VERIFY_APARTMENT_LOADING = "VERIFY_APARTMENT_LOADING";
export const VERIFY_APARTMENT_SUCCESS = "VERIFY_APARTMENT_SUCCESS";
export const VERIFY_APARTMENT_FAIL = "VERIFY_APARTMENT_FAIL";
