export const REGISTER_LOADING ='REGISTER_LOADING';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const LOGOUT = 'LOGOUT';

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const UPLOAD_SHORTLET_LOADING = "UPLOAD_SHORTLET_LOADING";
export const UPLOAD_SHORTLET_SUCCESS = "UPLOAD_SHORTLET_SUCCESS";
export const UPLOAD_SHORTLET_FAIL = "UPLOAD_SHORTLET_FAIL";

export const FETCH_SHORTLET_LOADING = "FETCH_SHORTLET_LOADING";
export const FETCH_SHORTLET_SUCCESS = "FETCH_SHORTLET_SUCCESS";
export const FETCH_SHORTLET_FAIL = "FETCH_SHORTLET_FAIL";

export const FETCH_ONE_SHORTLET_LOADING = "FETCH_ONE_SHORTLET_LOADING";
export const FETCH_ONE_SHORTLET_SUCCESS = "FETCH_ONE_SHORTLET_SUCCESS";
export const FETCH_ONE_SHORTLET_FAIL = "FETCH_ONE_SHORTLET_FAIL";

export const GETLINK_FAIL = "GETLINK_FAIL";