import React from "react";
import classes from "./Terms.module.css";
import Header from "../../components/UI/Header/index";
import Footer from "../../components/UI/Footer";
import Button from "../../components/UI/Button";
const Terms = () => {
  return (
    <div>
      <Header />
      <div className={classes.body}>
        <h2>Terms & Conditions</h2>
        <h5>
          Please kindly read carefully to be properly guided on being a
          TravelBear landlord.
        </h5>
        <div className={classes.para}>
          <p>
            <h5> General Terms</h5>
            By accessing and booking an accommodation with TravelBear confirm
            that you are in agreement with and bound by the terms of service
            contained in the Terms & Conditions outlined below. These terms
            apply to the entire website and any email or other type of
            communication between you and TravelBear. Under no circumstances
            shall team be liable for any direct, indirect, special, incidental
            or consequential damages, including, but not limited to, loss of
            data or profit, arising out of the use, or the inability to use, the
            materials on this site, even if team or an authorized representative
            has been advised of the possibility of such damages. If your use of
            materials from this site results in the need for servicing, repair
            or correction of equipment or data, you assume any costs thereof.
            TravelBear will not be responsible for any outcome that may occur
            during the course of usage of our resources. We reserve the rights
            to change prices and revise the resources usage policy at any
            moment.
          </p>
          <p>
            <h5>License</h5> TravelBear grants you a revocable, non-exclusive,
            non-transferable, limited license to download, install and use the
            TravelBear strictly in accordance with the terms of this agreement .
            These Terms & Conditions are a contract between you and TravelBear
            License grants you a revocable, non-exclusive, non-transferable,
            limited license to download, install and use them strictly in
            accordance with the terms of this Agreement. These Terms &
            Conditions are a contract between you and ("we," "our," or "us")
            grants you a revocable, non-exclusive, non-transferable, limited
            license to download, install and use them strictly in accordance
            with the terms of this Agreement.
            <br />
            <h5> Definitions and key terms For this</h5>
            Terms & Conditions:
            <br /> • Cookie: small amount of data generated by a website and
            saved by your web browser. It is used to identify your browser,
            provide analytics, and remember information about you such as your
            language preference or login information.
            <br /> • Company: when this policy mentions "Company," "we," "us,"
            or "our," it refers to information under this Privacy Policy.
            <br /> • Customer: refers to the company, organization or person
            that signs up to use the relationships with your consumers or
            service users Service to manage the <br /> • Device: any internet
            connected device such as a phone, tablet, computer or any other
            device that can be used to visit and use the services.
            <br /> • IP address: Every device connected to the Internet is
            assigned a number known as an Internet protocol (IP) address. These
            numbers are usually assigned in geographic blocks. An IP address can
            often be used to identify the location from which a device is
            connecting to the Internet.
            <br /> • Personnel: refers to those individuals who are employed by
            one of the parties. or are under contract to perform a service on
            behalf of TravelBear.
          </p>
        </div>
        <aside className={classes.btn}>
          <div>
            <Button primary name="Yes, I agree" />
            <Button link name="No, I disagree" />
          </div>
        </aside>
      </div>
      <Footer />
    </div>
  );
};

export default Terms;
